name: Update Sitemap
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch: # இது நீங்கள் கைமுறையாக ரன் செய்ய உதவும்

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install node-fetch
      - run: node scripts/generate-sitemap.js
      - name: Commit and Push
        run: |
          git config --global user.name 'Sitemap Bot'
          git config --global user.email 'bot@kalvivaanam.in'
          git add sitemap.xml
          git commit -m "Automated sitemap update" || exit 0
          git push
